# Generated by Django 4.0.5 on 2022-06-20 09:39

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('primary_body_part', models.CharField(choices=[('Abs', 'Abs'), ('Back', 'Back'), ('Biceps', 'Biceps'), ('Cardio', 'Cardio'), ('Chest', 'Chest'), ('Legs', 'Legs'), ('Shoulders', 'Shoulders'), ('Triceps', 'Triceps'), ('Other', 'Other')], max_length=20)),
                ('other_body_parts', models.CharField(blank=True, max_length=200, null=True)),
                ('view_link', models.URLField(blank=True, max_length=500, null=True)),
                ('suggestions', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['primary_body_part', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('count', models.PositiveSmallIntegerField(blank=True, help_text='Enter count per rep, or keep rep 1 and total count', null=True)),
                ('repetitions', models.PositiveSmallIntegerField(default=1)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('duration', models.DurationField(blank=True, help_text='Duration in hh:mm:ss', null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['time_stamp', 'exercise', 'user'],
            },
        ),
    ]
