name: Test Tracking site

on:
  push:
    branches:
      - main

jobs:
  tracking_site_test:
    runs-on: ubuntu-latest
    steps:
      - users: actions/checout@v2

      - name: Setup Python version
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python3 manage.py collectstatic

      - name: Run django unit tests
        run: |
          python3 manage.py test

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            setup.log
            debug.log
            !venv/