# Generated by Django 4.0.5 on 2022-07-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_multiproductcollectivetracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_in_site',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='only_for_search',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.BooleanField(default=False),
        ),
    ]
