# Generated by Django 4.0.5 on 2022-09-02 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_only_for_search_alter_product_site'),
        ('products', '0005_multiproductcollectivetracking_name_and_more'),
    ]

    operations = [
    ]
